id: d331607e9a3e411c9bf291ad2e184688
initial_creation_type: ocr
source_metadata:
  volumes:
    5c8f0212238f4a26b564e276063633b5:
      base_file: v063.txt
      image_group_id: I1PD95909
      title: མདོ་ཀུན་ལས་བཏུས་པ།
      total_pages: 1902
      volume_number: 64
